[[repositories]]
name = "isacikgoz/tldr"
file = "tldr"
comment = "quick help for any command"
tags = ["help"]

[[repositories]]
name = "jorgerojas26/lazysql"
file = "lazysql"
comment = "fast sql TUI"
tags = ["databases"]

[[repositories]]
name = "jesseduffield/lazygit"
file = "lazygit"
comment = "fast git TUI"
tags = ["scm"]

[[repositories]]
name = "schollz/croc"
file = "croc"
comment = "transfer files and folders"
tags = ["networking", "sharing"]

[[repositories]]
name = "chriswalz/bit"
file = "bit"
comment = "a modern git cli"
tags = ["scm"]

[[repositories]]
name = "sachaos/viddy"
file = "viddy"
comment = "a modern watch command"
tags = ["utils", "shell"]

[[repositories]]
name = "akavel/up"
file = "up"
comment = "run command |& up then use grep awk etc"
tags = ["utils", "shell"]

[[repositories]]
name = "sharkdp/fd"
file = "fd"
comment = "a simple, fast and user-friendly alternative to 'find'"
tags = ["utils", "shell"]

[[repositories]]
name = "lsd-rs/lsd"
file = "lsd"
comment = "next gen ls command"
tags = ["utils", "shell"]

[[repositories]]
name = "sharkdp/bat"
file = "bat"
comment = "improved cat"
tags = ["utils", "shell"]

[[repositories]]
name = "junegunn/fzf"
file = "fzf"
comment = "command-line fuzzy finder"
tags = ["utils", "shell"]

[[repositories]]
name = "BurntSushi/ripgrep"
file = "rg"
comment = "much improved grep"
tags = ["utils", "shell"]

[[repositories]]
name = "Wilfred/difftastic"
file = "difft"
comment = "structural diff that understands syntax"
tags = ["development", "shell"]
