[[repositories]]
name = "tulir/gomuks"
file = "gomuks"
comment = "a TUI matrix client"
tags = ["chat", "fediverse"]

[[repositories]]
name = "yudai/gotty"
file = "gotty"
comment = "share terminal as a web application"
tags = ["sharing"]

[[repositories]]
name = "humanlogio/humanlog"
file = "humanlog"
comment = "logs for humans to read"
tags = ["util", "devops"]

[[repositories]]
name = "go-jira/jira"
file = "jira"
comment = "jira client for command line"
tags = ["development"]

[[repositories]]
name = "six-ddc/plow"
file = "plow"
comment = "a high performance http bechmarking tool"
tags = ["networking", "devops"]

[[repositories]]
name = "fusion/pngsource"
file = "pngsource"
comment = "embed source code in png files"
tags = ["utils"]

[[repositories]]
name = "cespare/reflex"
file = "reflex"
comment = "run a command when files change"
tags = ["utils", "shell", "devops"]

[[repositories]]
name = "jqlang/jq"
file = "jq"
comment = "command-line JSON processor"
tags = ["util", "shell", "data handling"]

[[repositories]]
name = "itchyny/gojq"
file = "gojq"
comment = "pure go implementation of jq"
tags = ["util", "shell", "data handling"]

[[repositories]]
name = "noahgorstein/jqp"
file = "jqp"
comment = "a TUI playground for jq"
tags = ["util", "shell", "data handling"]

[[repositories]]
name = "johnkerl/miller"
file = "mlr"
comment = "like awk, sed, cut, join, and sort for CSV, TSV, and JSON"
tags = ["util", "shell", "data handling"]

[[repositories]]
name = "antonmedv/fx"
file = "fx"
comment = "json and yaml viewer and processor"
tags = ["util", "shell", "data handling"]

[[repositories]]
name = "gohugoio/hugo"
file = "hugo"
comment = "static site generator"
tags = ["web"]

[[repositories]]
name = "syncthing/syncthing"
file = "syncthing"
comment = "continuous file synchronization"
tags = ["networking"]

[[repositories]]
name = "kubernetes/minikube"
file = "minikube"
comment = "local Kubernetes cluster"
tags = ["devops"]

[[repositories]]
name = "ogham/dog"
file = "dog"
comment = "command-line DNS client"
tags = ["devops"]

[[repositories]]
name = "chmln/sd"
file = "sd"
comment = "find & replace CLI"
tags = ["shell"]

[[repositories]]
name = "denisidoro/navi"
file = "navi"
comment = "interactive cheatsheet tool for the command-line"
tags = ["shell", "help"]

[[repositories]]
name = "pemistahl/grex"
file = "grex"
comment = "regex commonality builder"
tags = ["shell", "help"]

[[repositories]]
name = "zellij-org/zellij"
file = "zellij"
comment = "terminal workspace with batteries included"
tags = ["shell"]

[[repositories]]
name = "sayanarijit/xplr"
file = "xplr"
comment = "hackable, minimal, fast TUI file explorer"
tags = ["shell"]

[[repositories]]
name = "orf/gping"
file = "gping"
comment = "ping with graph and jitter"
tags = ["shell", "networking"]

[[repositories]]
name = "bootandy/dust"
file = "dust"
comment = "more intuitive version of du in rust"
tags = ["shell"]

[[repositories]]
name = "Byron/dua-cli"
file = "dua"
comment = "view disk space usage and delete unwanted data (hint: dua i)"
tags = ["shell"]

[[repositories]]
name = "muesli/duf"
file = "duf"
comment = "display disks, mounts, etc with stats"
tags = ["shell"]

[[repositories]]
name = "ducaale/xh"
file = "xh"
comment = "send http requests: xh post myvar=myvalue etc"
tags = ["shell"]

[[repositories]]
name = "fatedier/frp"
file = "frp"
command = "frps"
utils = ["frps", "frpc"]
comment = "reverse proxy to help you expose a local server"
tags = ["networking"]

[[repositories]]
name = "rclone/rclone"
file = "rclone"
comment = "sync files and directories to and from different cloud storage providers"
tags = ["networking"]

[[repositories]]
name = "martinvonz/jj"
file = "jj"
comment = "Git-compatible VCS that is both simple and powerful"
tags = ["development"]

[[repositories]]
name = "alexpasmantier/television"
file = "tv"
comment = "general purpose fuzzy finder TUI"
tags = ["shell"]

[[repositories]]
name = "hengyoush/kyanos"
file = "kyanos"
comment = "visualize and analyze packets in the kernel"
tags = ["development", "networking"]

[[repositories]]
name = "Hakky54/certificate-ripper"
file = "crip"
comment = "extract server certificates"
tags = ["security", "networking"]

[[repositories]]
name = "homeport/dyff"
file = "dyff"
comment = "diff/convert yaml and json"
tags = ["utils", "devops"]

[[repositories]]
name = "astral-sh/uv"
file = "uv"
utils = ["uvx"]
comment = "fast Python package and project manager"
tags = ["utils"]

[[repositories]]
name = "nushell/nushell"
file = "nu"
comment = "data handling shell"
tags = ["utils", "shell"]
