[[repositories]]
name = "tulir/gomuks"
file = "gomuks"
comment = "a TUI matrix client"

[[repositories]]
name = "yudai/gotty"
file = "gotty"
comment = "share terminal as a web application"

[[repositories]]
name = "humanlogio/humanlog"
file = "humanlog"
comment = "logs for humans to read"

[[repositories]]
name = "go-jira/jira"
file = "jira"
comment = "jira client for command line"

[[repositories]]
name = "six-ddc/plow"
file = "plow"
comment = "a high performance http bechmarking tool"

[[repositories]]
name = "fusion/pngsource"
file = "pngsource"
comment = "embed source code in png files"

[[repositories]]
name = "cespare/reflex"
file = "reflex"
comment = "run a command when files change"

[[repositories]]
name = "getsops/sops"
file = "sops"
comment = "flexible tool for managing secrets"

[[repositories]]
name = "itchyny/gojq"
file = "gojq"
comment = "pure go implementation of jq"

[[repositories]]
name = "noahgorstein/jqp"
file = "jqp"
comment = "a TUI playground for jq"

[[repositories]]
name = "johnkerl/miller"
file = "mlr"
comment = "like awk, sed, cut, join, and sort for CSV, TSV, and JSON"

[[repositories]]
name = "antonmedv/fx"
file = "fx"
comment = "json and yaml viewer and processor"
